version: "3.8"
services:
  database:
    image: postgres:14.11-alpine
    environment:
      POSTGRES_PASSWORD: finmid
    ports:
      - 5432:5432
    volumes:
      - ./data:/docker-entrypoint-initdb.d
